#_________ WELCOME ALL OF YOU ON COMPUTER SOFT SKILLS CHANNEL __________

#........................ WISH HAPPY DIWALI USING PYHON TURTLE GRAPHICS ......................


import turtle

# Turtle Window
wn = turtle.Screen()
wn.setup(800,750)
wn.title("Computer Soft Skills: HAPPY DIWALI")

t=turtle.Turtle()
t.speed(5)
t.pensize(20)


#DRAW LETTER
#Draw H

t.color("RED")
t.shape("triangle")
t.penup()
t.backward(250)
t.left(90)
t.pendown()
t.forward(100)
t.backward(50)
t.right(90)
t.forward(45)
t.left(90)
t.forward(45)
t.backward(100)
t.right(90)

#Draw A
t.color("blue")
t.penup()
t.forward(30)
t.left(90)
t.pendown()
t.forward(100)
t.right(90)
t.forward(50)
t.right(90)
t.forward(50)
t.right(90)
t.forward(50)
t.right(180)
t.forward(50)
t.right(90)
t.forward(50)
t.left(90)

#draw p
t.color("green")
t.penup()
t.forward(30)
t.left(90)
t.pendown()
t.forward(100)
t.right(90)
t.forward(50)
t.right(90)
t.forward(50)
t.right(90)
t.forward(50)
t.right(180)

#draw P
t.color("purple")
t.penup()
t.forward(80)
t.left(90)
t.pendown()
t.forward(100)
t.right(90)
t.forward(50)
t.right(90)
t.forward(50)
t.right(90)
t.forward(50)
t.right(180)

#Draw Y
t.color("orangered")
t.penup()
t.forward(90)
t.left(90)
t.pendown()
t.forward(75)
t.left(90)
t.forward(30)
t.right(90)
t.forward(30)
t.backward(30)
t.right(90)
t.forward(60)
t.left(90)
t.forward(30)
t.right(90)


#Draw D
t.color("orange")
t.penup()
t.goto(170,-150)
t.backward(470)
t.left(90)
t.pendown()
t.forward(100)
t.right(90)
t.forward(50)
t.right(90)
t.forward(100)
t.right(90)
t.forward(50)
t.left(180)

#Draw I
t.color("red")
t.penup()
t.goto(210,-70)
t.backward(430)
t.right(90)
t.pendown()
t.forward(100)
t.left(90)

#Draw W
t.color("green")
t.penup()
t.goto(220,-60)
t.backward(400)
t.right(90)
t.pendown()
t.forward(100)
t.left(90)
t.forward(30)
t.left(90)
t.forward(100)
t.backward(100)
t.right(90)
t.forward(30)
t.left(90)
t.forward(100)
t.right(90)


#Draw A
t.color("magenta")
t.penup()
t.goto(325,-160)
t.backward(370)
t.left(90)
t.pendown()
t.forward(100)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.backward(50)
t.right(90)
t.forward(50)
t.right(90)

#Draw L
t.color("crimson")
t.penup()
t.goto(-340,-60)
t.backward(330)
t.left(90)
t.pendown()
t.forward(100)
t.left(90)
t.forward(50)
t.right(90)

#Draw I
t.color("blue")
t.penup()
t.goto(80,-450)
t.backward(300)
t.left(180)
t.pendown()
t.forward(100)

turtle.done()

